### ISSUE TITLE
Error counters

### ISSUE THREAD

**Issue by bbrutman** [outbrain/Aletheia#12]
I am trying to aggregate all errors generated by AletheiaKafka producer and am unable to do that with a wild card since the below counter is part of the hierarchy but is not an error counter.
 
Please change the location of the following counter <producer>.Aletheia.DatumTypes.<topic>.DatumProducer.RecommendationKafka_Chidc.Data.Tx.KafkaTopicProductionEndPoint.Send.Attempts.Failures.Duration.count so that all counters below ...Send.Attempts.Failures can be aggregated.

**Comment by staslev** [comment]
We've changed the producer's failure metrics sub tree in `aletheia-0.42`, so it should be easier to make these kinds of aggregations.
