### ISSUE TITLE
Consider changing the dependency on aletheia-core to provided

### ISSUE THREAD

**Issue by izikshmulewitz** [outbrain/Aletheia#9]
When writing a new consumption/production endpoint, one brings a versioned dependency on aletheia-core. On the other hand when using aletheia in a project the user creates a dependency to aletheia-core and all of his used consumption endpoints jars. If those jars are dependent on aletheia-core the user might face some versioning issues.
For instance upgrading aletheia-core version does not change its version since the aletheia-kafka brought the old version.

A possible solution will be to change the dependency on aletheia-core in the aletheia-kafka to provided.

**Comment by staslev** [comment]
Sounds fair, we'll make it happen for next release.
